from pathlib import Path


SOURCE_FILE = Path(__file__).with_name("dictionary.csv")
FILE_PATH = SOURCE_FILE  # Backward-compatible alias.
OUTPUT_DIR = Path(__file__).with_name("output")
VISUALIZATION_MODE = "spherical"  # flat | spherical
FOCUS_COLUMN = "Word"
DEFINITION_COLUMN = "Definition"
POS_COLUMN = "POS"
USE_EMBEDDINGS = True
DIMENSIONS = 3
USE_UMAP = True
N_CLUSTERS = 20
K_NEIGHBORS = 10

MAX_FEATURES = 5000
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
RANDOM_STATE = 42
PREVIEW_POINT_THRESHOLD = 10000
MAX_EDGE_RENDER = 2000
LARGE_DATA_THRESHOLD = 50000
GRAPH_SEARCH_DIMS = 64

UMAP_N_NEIGHBORS = 30
UMAP_MIN_DIST = 0.45
UMAP_SPREAD = 2.0

COORDINATE_SCALE = 3.0

ENABLE_3D_NODE_SPREAD = True
DISPLAY_MIN_DISTANCE = 0.15
DISPLAY_DISTANCE_NEIGHBORS = 6
DISPLAY_DISTANCE_PASSES = 2
MAX_DISPLAY_ADJUST_POINTS = 12000

MARKER_SIZE_3D = 2
MARKER_OPACITY_3D = 0.55
FIGURE_WIDTH = 1400
FIGURE_HEIGHT = 1000
SCENE_ASPECTMODE = "cube"
CAMERA_EYE_X = 1.8
CAMERA_EYE_Y = 1.8
CAMERA_EYE_Z = 1.4

PLOT_AUTO_OPEN = True
USE_EXISTING_OUTPUTS = True  # When True, open the last generated outputs instead of rerunning the pipeline.
PLOT_2D_FILE = OUTPUT_DIR / "semantic_map_2d.html"
PLOT_3D_FILE = OUTPUT_DIR / "semantic_map_3d.html"
NODES_FILE = OUTPUT_DIR / "nodes.csv"
EDGES_FILE = OUTPUT_DIR / "edges.csv"
RUN_METADATA_FILE = OUTPUT_DIR / "run_metadata.json"
RUN_HISTORY_FILE = OUTPUT_DIR / "run_history.json"

SPHERICAL_OUTPUT_DIR = OUTPUT_DIR / "spherical"
SPHERICAL_RUNS_DIR = OUTPUT_DIR / "runs"
SPHERICAL_LAUNCHER_HTML = OUTPUT_DIR / "spherical_launcher.html"
SPHERICAL_ROOT_HTML = SPHERICAL_OUTPUT_DIR / "sphere_level0.html"
SPHERICAL_HIERARCHY_FILE = SPHERICAL_OUTPUT_DIR / "hierarchy_nodes.csv"
SPHERICAL_COORDS_FILE = SPHERICAL_OUTPUT_DIR / "spherical_coords.csv"
SPHERICAL_MEMBERSHIPS_FILE = SPHERICAL_OUTPUT_DIR / "secondary_memberships.csv"
SPHERICAL_SURFACE_POINTS_FILE = SPHERICAL_OUTPUT_DIR / "surface_points.csv"
SPHERICAL_SURFACE_HTML = SPHERICAL_OUTPUT_DIR / "Englictionary.html"
MAX_RECENT_RUNS = 8

SPHERE_TOP_CLUSTERS = 12
SPHERE_SUBCLUSTERS_PER_CLUSTER = 6
SPHERE_MIN_SUBCLUSTER_SIZE = 30
SPHERE_SECONDARY_MEMBERSHIPS = 2

SPHERE_TOP_RADIUS = 1.0
SPHERE_SUB_RADIUS = 1.08
SPHERE_WORD_RADIUS = 1.16
SPHERE_PATCH_RADIUS_SUB = 0.14
SPHERE_PATCH_RADIUS_WORD = 0.08
SPHERE_LOCAL_EDGE_K = 5

# Full-surface spherical mode settings (all rows on one globe)
SPHERE_FULL_SURFACE = True
SPHERE_CLUSTER_COUNT = 56
SPHERE_RENDER_RADIUS = 285.0
SPHERE_POINT_LIFT = 1.012
SPHERE_NODE_PIXEL_SIZE = 2.6
SPHERE_NODE_ANGULAR_SPACING = 0.0032
SPHERE_CLUSTER_ANGULAR_PADDING = 0.022
SPHERE_CLUSTER_MAX_ANGULAR_RADIUS = 0.5
SPHERE_CLUSTER_REPEL_STEPS = 220
SPHERE_INCLUDE_DEFINITION_IN_HTML = False

# Large payload safeguards for browser stability.
SPHERE_DEFINITION_MAX_POINTS = 25000
